[project]
name = "renrence-draw"
version = "0.1.0"
description = "人人测抽签程序"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pyside6>=6.9.0",
    "qt-material>=2.14",
]
